### ISSUE TITLE
Compatibility with Kanban plugin: add TODOs to first column

### ISSUE THREAD

**Issue by huyz** [shichongrui/obsidian-rollover-daily-todos#33]
For compatibility with https://github.com/mgmeyers/obsidian-kanban , could the TODO items be added to the end of the first H2 heading block?  This would make the TODO be in the first Kanban column rather than the completed column.

Right now, this is what happens:
```
## #todo

- [ ] Pre-existing todo

## #todo in progress

## Done

**Complete**

- [ ] Todo from yesterday
```

Ideally, this is what should result:
```
## #todo

- [ ] Pre-existing todo
- [ ] Todo from yesterday

## #todo in progress

## Done

**Complete**

```

**Comment by tim-hilt** [comment]
Fixed by #80
